replicaCount: 1

image:
  repository: vegito/userapi
  pullPolicy: IfNotPresent
  tag: "latest"

container:
  env:
    - name: db_root_password
      value: "root@FpO"
    - name: db_name
      value: userapi
    - name: MYSQL_SERVICE_HOST
      value: my-mysql.default.svc.cluster.local
    - name: MYSQL_SERVICE_PORT
      value: "3306"

imagePullSecrets: []
nameOverride: "userapi"
fullnameOverride: "userapi"

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
